// src/components/ReviewPanel.tsx
"use client";

import { useState, useEffect } from "react";
import { authFetch } from "@/lib/api";
import type { AgentResult } from "@/app/console/page";
import ReactMarkdown from "react-markdown";
import { CheckCircle2, XCircle } from "lucide-react";

type Decision = "approved" | "rejected" | null;

export default function ReviewPanel({
  result,
  onClear,
}: {
  result: AgentResult | null;
  onClear: () => void;
}) {
  const [editedText, setEditedText] = useState("");
  const [isEditing, setIsEditing] = useState(false);
  const [decision, setDecision] = useState<Decision>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [finalDocxPath, setFinalDocxPath] = useState("");

  useEffect(() => {
    if (result) {
      setEditedText(result.response);
      setIsEditing(false);
      setDecision(null);
      setError("");
      setFinalDocxPath(result.docxPath);
    }
  }, [result]);

  if (!result) {
    return (
      <div className="h-full p-6">
        <h1 className="text-2xl font-semibold text-[var(--text-primary)]">Review & Sign-Off</h1>
        <p className="mt-1 text-sm text-[var(--text-secondary)]">
          Every AI deliverable waits here for a named approver.
        </p>
        <div className="flex items-center justify-center h-[60%]">
          <p className="text-sm text-[var(--text-muted)] max-w-sm text-center leading-relaxed">
            No output pending review yet. Ask SOVARA something in the AI Assistant
            tab first -- the result will appear here for sign-off.
          </p>
        </div>
      </div>
    );
  }

  const handleApprove = () => setDecision("approved");
  const handleReject = () => {
    setDecision("rejected");
    onClear();
  };

  const handleSaveModified = async () => {
    setSaving(true);
    setError("");
    try {
      const res = await authFetch("/api/review/save-modified", {
        method: "POST",
        body: JSON.stringify({ text: editedText }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => null);
        throw new Error(body?.detail ?? "Failed to save modified document");
      }
      const data = await res.json();
      setFinalDocxPath(data.docx_path);
      setDecision("approved");
      setIsEditing(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <div className="p-6 pb-0">
        <h1 className="text-2xl font-semibold text-[var(--text-primary)]">Review & Sign-Off</h1>
        <p className="mt-1 text-sm text-[var(--text-secondary)]">
          Every AI deliverable waits here for a named approver.
        </p>
      </div>

      <div className="flex-1 flex gap-4 p-6 overflow-hidden">
        <div className="w-56 shrink-0">
          <span className="text-xs font-medium uppercase tracking-wide" style={{ color: "var(--text-faint)" }}>
            Awaiting sign-off
          </span>
          <div
            className="mt-2 rounded-xl border p-3"
            style={{
              borderColor: decision ? "var(--border)" : "var(--accent)",
              background: "var(--panel)",
            }}
          >
            <p className="text-sm font-medium text-[var(--text-primary)]">
              Approval note
            </p>
            <p className="text-xs mt-0.5" style={{ color: "var(--text-muted)" }}>
              {decision === "approved" ? "Signed off" : decision === "rejected" ? "Rejected" : "Just now"}
            </p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto">
          <div
            className="rounded-xl border p-5"
            style={{ borderColor: "var(--border)", background: "var(--panel)" }}
          >
            <div className="flex items-center justify-between text-xs font-mono" style={{ color: "var(--text-faint)" }}>
              <span>DRAFT - GENERATED BY AGENT</span>
            </div>

            <div className="mt-3">
              {isEditing ? (
                <textarea
                  className="w-full min-h-[300px] resize-y rounded-lg p-3 text-[15px] leading-relaxed focus:outline-none"
                  style={{ background: "var(--bg)", border: "1px solid var(--border)", color: "var(--text-primary)" }}
                  value={editedText}
                  onChange={(e) => setEditedText(e.target.value)}
                />
              ) : (
                <div className="text-[15px] text-[var(--text-primary)] leading-relaxed [&>p]:mb-3 [&>p:last-child]:mb-0 [&_strong]:font-semibold [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-3 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mb-3 [&_li]:mb-1">
                  <ReactMarkdown>{editedText}</ReactMarkdown>
                </div>
              )}
            </div>

            {result.citations.length > 0 && !isEditing && (
              <div className="mt-4 flex flex-wrap gap-2">
                {result.citations.map((c, i) => (
                  <span
                    key={i}
                    className="text-xs font-mono px-2 py-1 rounded"
                    style={{ background: "var(--accent-soft-bg)", color: "var(--accent-2)" }}
                  >
                    {c.source} - {c.score.toFixed(3)}
                  </span>
                ))}
              </div>
            )}
          </div>

          {error && (
            <div
              className="mt-3 rounded-xl border p-3 text-sm"
              style={{ borderColor: "var(--error-border)", background: "var(--error-bg)", color: "var(--error-text)" }}
            >
              {error}
            </div>
          )}
        </div>

        <div className="w-64 shrink-0">
          <span className="text-xs font-medium uppercase tracking-wide" style={{ color: "var(--text-faint)" }}>
            Decision
          </span>

          <div
            className="mt-2 rounded-xl border p-4"
            style={{ borderColor: "var(--border)", background: "var(--panel)" }}
          >
            {decision === "approved" ? (
              <div className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 mt-0.5 shrink-0" style={{ color: "var(--accent-2)" }} />
                <div>
                  <p className="text-sm font-medium" style={{ color: "var(--accent-2)" }}>Approved and signed</p>
                  <p className="mt-1 text-xs font-mono" style={{ color: "var(--text-muted)" }}>{finalDocxPath}</p>
                </div>
              </div>
            ) : decision === "rejected" ? (
              <div className="flex items-start gap-2">
                <XCircle className="h-4 w-4 mt-0.5 shrink-0" style={{ color: "var(--error-text)" }} />
                <p className="text-sm font-medium" style={{ color: "var(--error-text)" }}>Rejected</p>
              </div>
            ) : isEditing ? (
              <div className="flex flex-col gap-2">
                <button
                  onClick={handleSaveModified}
                  disabled={saving || !editedText.trim()}
                  className="text-sm font-medium py-2.5 rounded-lg transition-opacity hover:opacity-90 disabled:opacity-30 disabled:cursor-not-allowed"
                  style={{ background: "var(--accent)", color: "var(--accent-fg)" }}
                >
                  {saving ? "Saving..." : "Save as final"}
                </button>
                <button
                  onClick={() => setIsEditing(false)}
                  className="text-sm py-2 rounded-lg"
                  style={{ color: "var(--text-muted)" }}
                >
                  Cancel
                </button>
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                <button
                  onClick={handleApprove}
                  className="text-sm font-medium py-2.5 rounded-lg transition-opacity hover:opacity-90"
                  style={{ background: "var(--accent)", color: "var(--accent-fg)" }}
                >
                  Approve and sign
                </button>
                <button
                  onClick={() => setIsEditing(true)}
                  className="text-sm font-medium py-2.5 rounded-lg border transition-colors"
                  style={{ borderColor: "var(--border)", color: "var(--text-primary)" }}
                >
                  Request changes
                </button>
                <button
                  onClick={handleReject}
                  className="text-sm font-medium py-2.5 rounded-lg border transition-colors"
                  style={{ borderColor: "var(--error-border)", color: "var(--error-text)" }}
                >
                  Reject
                </button>
              </div>
            )}
          </div>

          <p className="mt-3 text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>
            Your decision and time are written to the Activity Log.
          </p>
        </div>
      </div>
    </div>
  );
}
