"""
SOVARA AI — DOCX Generation Service

Converts the agent final text output into a real, structured
Word document (approval note). Handles markdown-style **bold**
segments anywhere within a line, not just whole-line headers.
"""

import os
import re
import uuid
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

OUTPUT_DIR = "generated_docs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

_BOLD_PATTERN = re.compile(r"\*\*(.+?)\*\*")


def _add_paragraph_with_bold(doc, text):
    """
    Adds a paragraph to the doc, rendering any **bold** segments
    within the text as actual bold runs, and stripping the asterisks.
    """
    paragraph = doc.add_paragraph()
    pos = 0
    for match in _BOLD_PATTERN.finditer(text):
        if match.start() > pos:
            paragraph.add_run(text[pos:match.start()])
        bold_run = paragraph.add_run(match.group(1))
        bold_run.bold = True
        pos = match.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])
    return paragraph


def generate_approval_note(content: str, title: str = "Approval Note") -> str:
    """
    Generates a formatted .docx approval note from the agent's final
    output text. Returns the file path of the generated document.
    """
    doc = Document()

    heading = doc.add_heading(title, level=1)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.add_run("Generated by SOVARA AI — Sovereign AI Reasoning Assistant").italic = True
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    for block in content.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        for line in block.split("\n"):
            line = line.strip()
            if line:
                _add_paragraph_with_bold(doc, line)

    unique_name = f"{uuid.uuid4()}.docx"
    file_path = os.path.join(OUTPUT_DIR, unique_name)
    doc.save(file_path)

    return file_path
