"""
SOVARA AI — DOCX Generation Service

Converts the agent final text output into a real, structured
Word document (approval note). Handles markdown-style **bold**
segments anywhere within a line, not just whole-line headers.
Also reads a generated note back as text, for the review queue.
"""

import os
import re
import uuid
from datetime import datetime, timezone
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

OUTPUT_DIR = "generated_docs"
os.makedirs(OUTPUT_DIR, exist_ok=True)
OUTPUT_ROOT = os.path.realpath(OUTPUT_DIR)

_BOLD_PATTERN = re.compile(r"\*\*(.+?)\*\*")
# Only files this service created: <uuid4>.docx
_NOTE_NAME = re.compile(
    r"^(?:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"          # older notes: <uuid>.docx
    r"|Approval_Note_(?:[A-Za-z0-9-]{1,40}_)?\d{8}-\d{6}_[0-9a-f]{8})\.docx$"    # Approval_Note_<source>_<time>_<id>.docx
)

# Paragraphs written before the content: title, "Generated by" line, blank line.
_HEADER_PARAGRAPHS = 3


def _add_paragraph_with_bold(doc, text):
    """
    Adds a paragraph to the doc, rendering any **bold** segments
    within the text as actual bold runs, and stripping the asterisks.
    """
    paragraph = doc.add_paragraph()
    pos = 0
    for match in _BOLD_PATTERN.finditer(text):
        if match.start() > pos:
            paragraph.add_run(text[pos:match.start()])
        bold_run = paragraph.add_run(match.group(1))
        bold_run.bold = True
        pos = match.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])
    return paragraph


def _note_filename(metadata: dict) -> str:
    """Readable, unique, filesystem-safe name, e.g. Approval_Note_V-301-Inspection_20260927-160012_7ff4b54d.docx"""
    source = os.path.splitext(metadata.get("source_filename") or "")[0]
    slug = re.sub(r"[^A-Za-z0-9]+", "-", source).strip("-")[:40].strip("-")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    short_id = (metadata.get("run_id") or uuid.uuid4().hex).replace("-", "")[:8].lower()
    return f"Approval_Note_{slug + '_' if slug else ''}{stamp}_{short_id}.docx"


def generate_approval_note(content: str, title: str = "Approval Note", metadata: dict | None = None) -> str:
    """
    Generates a formatted .docx approval note from the agent's final
    output text. Run details (who requested it, when, which model, which
    source document) are written by SOVARA from `metadata`, never by the
    model. Returns the file path of the generated document.
    """
    metadata = metadata or {}
    doc = Document()

    heading = doc.add_heading(title, level=1)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.add_run("Generated by SOVARA AI — Sovereign AI Reasoning Assistant").italic = True
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Run details as a table: tables aren't counted in doc.paragraphs, so the
    # header layout read back by read_approval_note() stays the same.
    rows = [
        ("Status", "DRAFT — pending sign-off in SOVARA"),
        ("Run ID", metadata.get("run_id") or "—"),
        ("Requested by", metadata.get("requested_by") or "—"),
        ("Generated (UTC)", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")),
        ("Model", metadata.get("model") or "—"),
        ("Source document", metadata.get("source_filename") or "—"),
    ]
    table = doc.add_table(rows=len(rows), cols=2)
    table.style = "Table Grid"
    for i, (label, value) in enumerate(rows):
        table.cell(i, 0).text = label
        table.cell(i, 1).text = str(value)
        for run in table.cell(i, 0).paragraphs[0].runs:
            run.bold = True

    doc.add_paragraph()

    for block in content.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        for line in block.split("\n"):
            line = line.strip()
            if line:
                _add_paragraph_with_bold(doc, line)

    file_path = os.path.join(OUTPUT_DIR, _note_filename(metadata))
    doc.save(file_path)

    return file_path


def resolve_note_path(name: str) -> str:
    """
    Maps a note file name (or a stored path ending in one) to a file inside
    OUTPUT_DIR. Only <uuid>.docx names are accepted, so this can't be used
    to read anything else on disk. Raises FileNotFoundError otherwise.
    """
    base = name.replace("\\", "/").rsplit("/", 1)[-1]
    if not _NOTE_NAME.match(base):
        raise FileNotFoundError("Not an approval note file name")
    full = os.path.realpath(os.path.join(OUTPUT_ROOT, base))
    if os.path.dirname(full) != OUTPUT_ROOT or not os.path.isfile(full):
        raise FileNotFoundError("Approval note file is missing on the server")
    return full


def read_approval_note(name: str) -> str:
    """
    Returns a generated note's content as Markdown-style text: one paragraph
    per line group, bold runs restored as **bold**. Title and header lines
    added by generate_approval_note() are skipped.
    """
    doc = Document(resolve_note_path(name))
    paragraphs = []
    for p in doc.paragraphs[_HEADER_PARAGRAPHS:]:
        text = "".join(f"**{r.text}**" if r.bold and r.text.strip() else r.text for r in p.runs).strip()
        if text:
            paragraphs.append(text)
    return "\n\n".join(paragraphs)