"""
SOVARA AI — DOCX Generation Service

Converts the agent final text output into a real, structured
Word document (approval note). Handles markdown-style **bold**
segments anywhere within a line, not just whole-line headers.
Also reads a generated note back as text, for the review queue.
"""

import os
import re
import uuid
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

OUTPUT_DIR = "generated_docs"
os.makedirs(OUTPUT_DIR, exist_ok=True)
OUTPUT_ROOT = os.path.realpath(OUTPUT_DIR)

_BOLD_PATTERN = re.compile(r"\*\*(.+?)\*\*")
# Only files this service created: <uuid4>.docx
_NOTE_NAME = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.docx$")

# Paragraphs written before the content: title, "Generated by" line, blank line.
_HEADER_PARAGRAPHS = 3


def _add_paragraph_with_bold(doc, text):
    """
    Adds a paragraph to the doc, rendering any **bold** segments
    within the text as actual bold runs, and stripping the asterisks.
    """
    paragraph = doc.add_paragraph()
    pos = 0
    for match in _BOLD_PATTERN.finditer(text):
        if match.start() > pos:
            paragraph.add_run(text[pos:match.start()])
        bold_run = paragraph.add_run(match.group(1))
        bold_run.bold = True
        pos = match.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])
    return paragraph


def generate_approval_note(content: str, title: str = "Approval Note") -> str:
    """
    Generates a formatted .docx approval note from the agent's final
    output text. Returns the file path of the generated document.
    """
    doc = Document()

    heading = doc.add_heading(title, level=1)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.add_run("Generated by SOVARA AI — Sovereign AI Reasoning Assistant").italic = True
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    for block in content.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        for line in block.split("\n"):
            line = line.strip()
            if line:
                _add_paragraph_with_bold(doc, line)

    unique_name = f"{uuid.uuid4()}.docx"
    file_path = os.path.join(OUTPUT_DIR, unique_name)
    doc.save(file_path)

    return file_path


def resolve_note_path(name: str) -> str:
    """
    Maps a note file name (or a stored path ending in one) to a file inside
    OUTPUT_DIR. Only <uuid>.docx names are accepted, so this can't be used
    to read anything else on disk. Raises FileNotFoundError otherwise.
    """
    base = name.replace("\\", "/").rsplit("/", 1)[-1]
    if not _NOTE_NAME.match(base):
        raise FileNotFoundError("Not an approval note file name")
    full = os.path.realpath(os.path.join(OUTPUT_ROOT, base))
    if os.path.dirname(full) != OUTPUT_ROOT or not os.path.isfile(full):
        raise FileNotFoundError("Approval note file is missing on the server")
    return full


def read_approval_note(name: str) -> str:
    """
    Returns a generated note's content as Markdown-style text: one paragraph
    per line group, bold runs restored as **bold**. Title and header lines
    added by generate_approval_note() are skipped.
    """
    doc = Document(resolve_note_path(name))
    paragraphs = []
    for p in doc.paragraphs[_HEADER_PARAGRAPHS:]:
        text = "".join(f"**{r.text}**" if r.bold and r.text.strip() else r.text for r in p.runs).strip()
        if text:
            paragraphs.append(text)
    return "\n\n".join(paragraphs)