"""
Deterministic field extraction and validation for scanned inspection reports.

Design:
- Values are never generated by an LLM. Every value is a real OCR line,
  paired with its label by layout (bounding boxes), so every field points to
  its exact source line and inherits that line's real PaddleOCR confidence.
- Validation checks use domain rules and recompute figures from the readings
  (corrosion rate, remaining life, margin to t-min) to catch OCR misreads
  that PaddleOCR still scored with high confidence.
- Expected fields that were not found are reported as such, never guessed.

Current schema: pressure vessel visual + UT thickness inspection reports.
Other document types will mostly return "not_found" fields.
"""

from __future__ import annotations

import re
from datetime import date, datetime
from difflib import SequenceMatcher
from typing import Any

# Lines below this PaddleOCR confidence need human review. Chosen from the
# V-301 sample: real misreads scored 0.862 and 0.869; 0.85 missed both.
REVIEW_CONFIDENCE = 0.90

# Readings within this margin (mm) above t-min are flagged as a warning.
TMIN_WARNING_MARGIN_MM = 1.0

# Tolerances when comparing the report's own figures with recomputed ones.
RATE_TOLERANCE_MM_PER_YEAR = 0.02
LIFE_TOLERANCE_YEARS = 0.2

LABEL_MATCH_RATIO = 0.8

FIELD_SPECS: list[dict[str, Any]] = [
    {"key": "report_no", "label": "Report No.", "aliases": ["Report No", "Report Number"], "kind": "text"},
    {"key": "equipment_tag", "label": "Equipment Tag", "aliases": ["Equipment Tag", "Tag No"], "kind": "tag"},
    {"key": "description", "label": "Description", "aliases": ["Description"], "kind": "text"},
    {"key": "unit_location", "label": "Unit / Location", "aliases": ["Unit / Location"], "kind": "text"},
    {"key": "inspection_date", "label": "Inspection date", "aliases": ["Inspection Date"], "kind": "date"},
    {"key": "inspection_type", "label": "Inspection type", "aliases": ["Inspection Type"], "kind": "text"},
    {"key": "design_code", "label": "Design code", "aliases": ["Design Code"], "kind": "design_code"},
    {"key": "shell_material", "label": "Shell material", "aliases": ["Shell Material"], "kind": "text"},
    {"key": "design_pressure", "label": "Design pressure", "aliases": ["Design Pressure"], "kind": "text"},
    {"key": "design_temperature", "label": "Design temperature", "aliases": ["Design Temperature"], "kind": "text"},
    {"key": "nominal_thickness", "label": "Nominal shell thickness", "aliases": ["Nominal Shell Thickness"], "kind": "mm"},
    {"key": "t_min", "label": "Minimum required thickness (t-min)", "aliases": ["Minimum Required (t-min)", "t-min"], "kind": "mm"},
    {"key": "corrosion_allowance", "label": "Corrosion allowance", "aliases": ["Corrosion Allowance"], "kind": "mm"},
    {"key": "previous_inspection", "label": "Previous inspection", "aliases": ["Previous Inspection"], "kind": "date"},
]

# Labels used only for pairing report-level figures in validation checks.
FIGURE_LABELS = {
    "stated_rate": ["Short-term corrosion rate"],
    "stated_life": ["Estimated remaining life"],
}

# Every known label, so a label is never mistaken for another label's value.
_ALL_LABELS = [a for spec in FIELD_SPECS for a in spec["aliases"]] + [
    a for aliases in FIGURE_LABELS.values() for a in aliases
] + ["Name", "Designation", "Signature", "Date", "Inspected by", "Reviewed/Approved by"]


# --------------------------------------------------------------------------
# Geometry and text helpers
# --------------------------------------------------------------------------

def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9]", "", text.lower())


def _ratio(a: str, b: str) -> float:
    return SequenceMatcher(None, _norm(a), _norm(b)).ratio()


def _cy(line: dict) -> float:
    return (line["bbox"][1] + line["bbox"][3]) / 2


def _cx(line: dict) -> float:
    return (line["bbox"][0] + line["bbox"][2]) / 2


def _height(line: dict) -> float:
    return max(line["bbox"][3] - line["bbox"][1], 1e-6)


def _same_row(a: dict, b: dict) -> bool:
    """True if b's vertical centre falls within a's row band (tolerates slight scan skew)."""
    tolerance = 0.6 * max(_height(a), _height(b))
    return abs(_cy(a) - _cy(b)) <= tolerance


def _is_label(text: str) -> bool:
    return any(_ratio(text, label) >= LABEL_MATCH_RATIO for label in _ALL_LABELS)


def _find_label(lines: list[dict], aliases: list[str]) -> dict | None:
    best, best_score = None, 0.0
    for line in lines:
        score = max(_ratio(line["text"], alias) for alias in aliases)
        if score >= LABEL_MATCH_RATIO and score > best_score:
            best, best_score = line, score
    return best


def _value_right_of(label: dict, lines: list[dict]) -> dict | None:
    """Nearest line to the right of the label on the same row that is not itself a label."""
    candidates = [
        l for l in lines
        if l is not label
        and l["page"] == label["page"]
        and l["bbox"][0] >= label["bbox"][2] - 0.005
        and _same_row(label, l)
    ]
    if not candidates:
        return None
    nearest = min(candidates, key=lambda l: l["bbox"][0])
    return None if _is_label(nearest["text"]) else nearest


def _source(line: dict) -> dict:
    return {
        "page": line["page"],
        "text": line["text"],
        "confidence": line["confidence"],
        "bbox": line["bbox"],
    }


# --------------------------------------------------------------------------
# Value parsing
# --------------------------------------------------------------------------

def _parse_mm(text: str) -> float | None:
    m = re.fullmatch(r"\s*(\d+(?:\.\d+)?)\s*mm\.?\s*", text, re.IGNORECASE)
    return float(m.group(1)) if m else None


def _parse_number(text: str) -> float | None:
    m = re.fullmatch(r"\s*(\d+(?:\.\d+)?)\s*", text)
    return float(m.group(1)) if m else None


def _parse_date(text: str) -> date | None:
    cleaned = text.strip().replace(" ", "")
    for fmt in ("%d-%m-%Y", "%d/%m/%Y", "%d.%m.%Y", "%d/%m/%y", "%d-%m-%y"):
        try:
            return datetime.strptime(cleaned, fmt).date()
        except ValueError:
            continue
    return None


def _validate_value(kind: str, text: str) -> tuple[Any, list[str]]:
    """Returns (parsed value, list of problems)."""
    if kind == "mm":
        value = _parse_mm(text)
        return value, ([] if value is not None else ["Expected a thickness in mm"])
    if kind == "date":
        value = _parse_date(text)
        return (value.isoformat() if value else None), ([] if value else ["Not a valid date"])
    if kind == "tag":
        ok = re.fullmatch(r"[A-Z]{1,4}-?\d{2,5}[A-Z]?", text.strip()) is not None
        return text.strip(), ([] if ok else ["Does not look like an equipment tag"])
    if kind == "design_code":
        ok = re.search(r"ASME.*Sec\.?\s*VIII\s*Div\.?\s*[123]", text, re.IGNORECASE) is not None
        problems = [] if ok else ["Not a recognised pressure-vessel design code (expected ASME Sec. VIII Div. 1/2/3)"]
        return text.strip(), problems
    return text.strip(), []


# --------------------------------------------------------------------------
# Field extraction
# --------------------------------------------------------------------------

def _extract_fields(lines: list[dict]) -> list[dict]:
    fields = []
    for spec in FIELD_SPECS:
        field = {"key": spec["key"], "label": spec["label"], "value": None, "parsed": None,
                 "status": "not_found", "reasons": [], "source": None}
        label_line = _find_label(lines, spec["aliases"])
        value_line = _value_right_of(label_line, lines) if label_line else None

        if value_line is None:
            field["reasons"].append("Label not found on the scan" if label_line is None else "No value next to the label")
        else:
            parsed, problems = _validate_value(spec["kind"], value_line["text"])
            if value_line["confidence"] < REVIEW_CONFIDENCE:
                problems.append(f"OCR confidence {value_line['confidence']:.3f} is below {REVIEW_CONFIDENCE:.2f}")
            field.update({
                "value": value_line["text"].strip(),
                "parsed": parsed,
                "status": "review" if problems else "ok",
                "reasons": problems,
                "source": _source(value_line),
            })
        fields.append(field)
    return fields


def _extract_signoff(lines: list[dict]) -> list[dict]:
    """
    Sign-off tables are laid out as columns ("Inspected by" / "Reviewed by")
    with row labels (Name, Designation, Date). Signatures are never read by
    OCR, so they are always marked for visual verification.
    """
    results: list[dict] = []
    inspected = _find_label(lines, ["Inspected by"])
    reviewed = _find_label(lines, ["Reviewed/Approved by", "Reviewed by", "Approved by"])
    columns = [(c, name) for c, name in ((inspected, "inspector"), (reviewed, "reviewer")) if c]
    if not columns:
        return results

    page = columns[0][0]["page"]
    header_y = max(c["bbox"][3] for c, _ in columns)
    page_lines = [l for l in lines if l["page"] == page and l["bbox"][1] >= header_y - 0.002]

    for row_label, suffix in (("Name", "name"), ("Designation", "designation"), ("Date", "date")):
        label_line = next((l for l in page_lines if _norm(l["text"]) == _norm(row_label)), None)
        row_items = [l for l in page_lines if label_line and l is not label_line and _same_row(label_line, l)
                     and l["bbox"][0] > label_line["bbox"][2]]
        for column, who in columns:
            # Assign row items to the nearest column header by horizontal position.
            in_col = [l for l in row_items
                      if min(columns, key=lambda c: abs(c[0]["bbox"][0] - l["bbox"][0]))[0] is column]
            key = f"{who}_{suffix}"
            label = f"{'Inspector' if who == 'inspector' else 'Reviewer'} {suffix}"
            if in_col:
                item = min(in_col, key=lambda l: l["bbox"][0])
                problems = []
                if item["confidence"] < REVIEW_CONFIDENCE:
                    problems.append(f"OCR confidence {item['confidence']:.3f} is below {REVIEW_CONFIDENCE:.2f}")
                if suffix == "date" and _parse_date(item["text"]) is None:
                    problems.append("Not a valid date")
                results.append({"key": key, "label": label, "value": item["text"].strip(),
                                "parsed": None, "status": "review" if problems else "ok",
                                "reasons": problems, "source": _source(item)})
            else:
                status = "pending" if who == "reviewer" else "not_found"
                reason = "Awaiting review and approval" if who == "reviewer" else "Not found on the scan"
                results.append({"key": key, "label": label, "value": None, "parsed": None,
                                "status": status, "reasons": [reason], "source": None})

    for _, who in columns:
        results.append({
            "key": f"{who}_signature",
            "label": f"{'Inspector' if who == 'inspector' else 'Reviewer'} signature",
            "value": None, "parsed": None, "status": "manual",
            "reasons": ["Signatures cannot be verified by OCR; check the scan visually"],
            "source": None,
        })
    return results


# --------------------------------------------------------------------------
# Thickness readings table
# --------------------------------------------------------------------------

_CML_RE = re.compile(r"^CML-?\s*\d+$", re.IGNORECASE)


def _extract_readings(lines: list[dict]) -> tuple[list[dict], dict]:
    anchors = [l for l in lines if _CML_RE.match(l["text"].strip())]
    if not anchors:
        return [], {}
    page = anchors[0]["page"]
    anchors = sorted([a for a in anchors if a["page"] == page], key=_cy)
    page_lines = [l for l in lines if l["page"] == page]

    # Column headers: the row just above the first reading.
    first_y = anchors[0]["bbox"][1]
    header_band = [l for l in page_lines if first_y - 0.06 < l["bbox"][3] <= first_y + 0.002]
    year_headers = sorted([l for l in header_band if re.fullmatch(r"(19|20)\d{2}", l["text"].strip())],
                          key=lambda l: int(l["text"]))
    columns: dict[str, dict] = {}
    for name, aliases in (("location", ["Location"]), ("nominal", ["Nominal"]), ("remarks", ["Remarks", "Remark"])):
        found = _find_label(header_band, aliases)
        if found:
            columns[name] = found
    if len(year_headers) >= 2:
        columns["previous"], columns["current"] = year_headers[-2], year_headers[-1]
    years = {"previous": int(year_headers[-2]["text"]) if len(year_headers) >= 2 else None,
             "current": int(year_headers[-1]["text"]) if len(year_headers) >= 2 else None}
    if not columns:
        return [], years

    pitch = (_cy(anchors[-1]) - _cy(anchors[0])) / max(len(anchors) - 1, 1) if len(anchors) > 1 else 0.03
    table_bottom = _cy(anchors[-1]) + pitch / 2

    # Assign each candidate cell to its nearest row anchor (robust to slight skew).
    rows: dict[int, list[dict]] = {i: [] for i in range(len(anchors))}
    for l in page_lines:
        if l in anchors or not (first_y - 0.002 <= _cy(l) <= table_bottom):
            continue
        i = min(range(len(anchors)), key=lambda k: abs(_cy(anchors[k]) - _cy(l)))
        if abs(_cy(anchors[i]) - _cy(l)) <= pitch * 0.5:
            rows[i].append(l)

    readings = []
    for i, anchor in enumerate(anchors):
        cells: dict[str, dict] = {}
        for l in rows[i]:
            col = min(columns, key=lambda c: abs(_cx(columns[c]) - _cx(l)))
            if col not in cells or abs(_cx(columns[col]) - _cx(l)) < abs(_cx(columns[col]) - _cx(cells[col])):
                cells[col] = l

        reading = {"cml": anchor["text"].strip().upper().replace(" ", ""), "location": None, "nominal": None,
                   "previous": None, "current": None, "remarks": None, "status": "ok", "reasons": [],
                   "confidence": anchor["confidence"], "sources": {"cml": _source(anchor)}}
        for col, line in cells.items():
            reading["sources"][col] = _source(line)
            reading["confidence"] = min(reading["confidence"], line["confidence"])
            if col in ("nominal", "previous", "current"):
                value = _parse_number(line["text"])
                if value is None:
                    reading["reasons"].append(f"{col.capitalize()} reading '{line['text']}' is not a number")
                reading[col] = value
            else:
                reading[col] = line["text"].strip()
            if line["confidence"] < REVIEW_CONFIDENCE:
                reading["reasons"].append(f"{col.capitalize()} has OCR confidence {line['confidence']:.3f}")
        for col in ("nominal", "previous", "current"):
            if col in columns and col not in cells:
                reading["reasons"].append(f"{col.capitalize()} reading not found")
        if reading["reasons"]:
            reading["status"] = "review"
        readings.append(reading)
    return readings, years


# --------------------------------------------------------------------------
# Validation checks
# --------------------------------------------------------------------------

def _stated_figure(lines: list[dict], key: str, unit_pattern: str) -> tuple[float | None, dict | None]:
    label = _find_label(lines, FIGURE_LABELS[key])
    value_line = _value_right_of(label, lines) if label else None
    if not value_line:
        return None, None
    numbers = re.findall(r"(\d+(?:\.\d+)?)\s*" + unit_pattern, value_line["text"].replace(" ", ""), re.IGNORECASE)
    return (float(numbers[-1]) if numbers else None), value_line


def _run_checks(fields: list[dict], readings: list[dict], years: dict, lines: list[dict]) -> list[dict]:
    checks: list[dict] = []
    by_key = {f["key"]: f for f in fields}
    t_min = by_key["t_min"]["parsed"] if by_key["t_min"]["status"] == "ok" else None
    nominal = by_key["nominal_thickness"]["parsed"] if by_key["nominal_thickness"]["status"] == "ok" else None

    insp = by_key["inspection_date"]["parsed"]
    prev = by_key["previous_inspection"]["parsed"]
    interval = None
    if insp and prev:
        interval = (date.fromisoformat(insp) - date.fromisoformat(prev)).days / 365.25
        checks.append({"id": "dates_order", "title": "Inspection dates in order",
                       "status": "pass" if interval > 0 else "fail",
                       "detail": f"Interval between inspections: {interval:.1f} years"})

    # Plausibility and per-reading rate / t-min checks
    shell_readings = []
    implausible = []
    for r in readings:
        cur, prv, nom = r["current"], r["previous"], r["nominal"]
        bad = False
        if cur is not None and nom is not None and cur > nom * 1.1:
            r["reasons"].append(f"Reading {cur} mm exceeds nominal {nom} mm by >10% (possible OCR misread)")
            bad = True
        if cur is not None and prv is not None and cur > prv + 0.3:
            r["reasons"].append("Current reading is higher than the previous one")
            bad = True
        if bad:
            r["status"] = "review"
            implausible.append(r["cml"])
        r["corrosion_rate"] = None
        if not bad and cur is not None and prv is not None and interval and interval > 0:
            r["corrosion_rate"] = round((prv - cur) / interval, 3)
        # Implausible readings are excluded so they can't hide the real worst case.
        if not bad and nominal is not None and nom == nominal and cur is not None:
            shell_readings.append(r)

    if readings:
        checks.append({"id": "plausible_readings", "title": "Thickness readings are plausible",
                       "status": "fail" if implausible else "pass",
                       "detail": (f"Excluded from calculations until corrected: {', '.join(implausible)}"
                                  if implausible else f"All {len(readings)} readings plausible")})
    excluded_note = f" ({len(implausible)} implausible reading(s) excluded)" if implausible else ""

    if t_min is not None and shell_readings:
        worst = min(shell_readings, key=lambda r: r["current"])
        margin = worst["current"] - t_min
        status = "fail" if margin <= 0 else "warn" if margin < TMIN_WARNING_MARGIN_MM else "pass"
        if implausible and status == "pass":
            status = "warn"  # can't confirm while a reading is unresolved
        checks.append({"id": "tmin_margin", "title": "Shell thickness above t-min",
                       "status": status,
                       "detail": f"Thinnest shell reading {worst['cml']}: {worst['current']} mm, "
                                 f"{margin:.1f} mm above t-min {t_min} mm{excluded_note}",
                       "cml": worst["cml"]})
        if status != "pass":
            worst["status"] = "review"
            worst["reasons"].append(f"Only {margin:.1f} mm above t-min")

    rated = [r for r in shell_readings if r.get("corrosion_rate") is not None]
    if rated:
        fastest = max(rated, key=lambda r: r["corrosion_rate"])
        computed_rate = fastest["corrosion_rate"]
        stated_rate, rate_line = _stated_figure(lines, "stated_rate", r"mm/y(?:ea)?r")
        if stated_rate is not None:
            ok = abs(stated_rate - computed_rate) <= RATE_TOLERANCE_MM_PER_YEAR
            checks.append({"id": "rate_consistency", "title": "Stated corrosion rate matches readings",
                           "status": "pass" if ok else "fail",
                           "detail": f"Report states {stated_rate} mm/year; recomputed from {fastest['cml']} "
                                     f"readings: {computed_rate:.2f} mm/year",
                           "source": _source(rate_line)})
        if t_min is not None and computed_rate > 0:
            computed_life = (fastest["current"] - t_min) / computed_rate
            stated_life, life_line = _stated_figure(lines, "stated_life", r"years?")
            if stated_life is not None:
                ok = abs(stated_life - computed_life) <= LIFE_TOLERANCE_YEARS
                checks.append({"id": "life_consistency", "title": "Stated remaining life matches readings",
                               "status": "pass" if ok else "fail",
                               "detail": f"Report states {stated_life} years; recomputed: {computed_life:.1f} years",
                               "source": _source(life_line)})

    low_lines = [l for l in lines if l["confidence"] < REVIEW_CONFIDENCE]
    checks.append({"id": "low_confidence_lines", "title": "Low-confidence OCR lines",
                   "status": "warn" if low_lines else "pass",
                   "detail": f"{len(low_lines)} line(s) below {REVIEW_CONFIDENCE:.2f} confidence"
                             + (": " + "; ".join(f"p{l['page']} '{l['text']}'" for l in low_lines[:5]) if low_lines else "")})
    return checks


# --------------------------------------------------------------------------
# Public entry point
# --------------------------------------------------------------------------

def extract_inspection_report(lines: list[dict]) -> dict:
    """
    lines: OCR lines from all pages, each {"page", "text", "confidence", "bbox"}.
    Returns fields, sign-off, readings and validation checks, every value
    traceable to its source OCR line.
    """
    fields = _extract_fields(lines)
    signoff = _extract_signoff(lines)
    readings, years = _extract_readings(lines)
    checks = _run_checks(fields, readings, years, lines)

    all_items = fields + signoff + readings
    return {
        "schema": "pressure_vessel_inspection_v1",
        "review_confidence": REVIEW_CONFIDENCE,
        "fields": fields,
        "signoff": signoff,
        "readings": readings,
        "reading_years": years,
        "checks": checks,
        "summary": {
            "needs_review": sum(1 for i in all_items if i["status"] == "review"),
            "not_found": sum(1 for i in all_items if i["status"] == "not_found"),
            "failed_checks": sum(1 for c in checks if c["status"] == "fail"),
            "warnings": sum(1 for c in checks if c["status"] == "warn"),
        },
    }